/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f407xx_gpio_drv.h"
#include "stm32f407Header.h"

int main(void)
{
   /*
    * P1:toggle the on board LED with some delay
    * case1: use push-pull configuration for the output pin
    * case2: use open drain configuration for the output pin
    */
	//as per schematic LED3,4,5 and 6 are connected to PD12,13,14 and 15 resp.

	/*
	 * P2: WAP to toggle on board LED whenever the on board button is pressed
	 */

	GPIO_Handle_t led[4];


	//for green LED
	led[0].GPIOPinConfig.GPIO_PinNum = PIN12;
	led[0].GPIOPinConfig.GPIOmode	=	OUTPUT_MODE;
	led[0].GPIOPinConfig.GPIOOutputType = OP_TYPE_PP;
	led[0].GPIOPinConfig.GPIOspeed = LOW;
	led[0].GPIOPinConfig.GPIOPullUpPullDown = NO_PU_NO_PD;

	led[0].pGPIO = GPIOD;


	//for orange LED
	led[1].GPIOPinConfig.GPIO_PinNum = PIN13;
	led[1].GPIOPinConfig.GPIOmode	=	OUTPUT_MODE;
	led[1].GPIOPinConfig.GPIOOutputType = OP_TYPE_OD;
	led[1].GPIOPinConfig.GPIOspeed = LOW;
	led[1].GPIOPinConfig.GPIOPullUpPullDown = NO_PU_NO_PD; //connect a resistor between vcc and PD 13 pin.

	led[1].pGPIO = GPIOD;


	//unable the GPIOD clock
	GPIO_PeriClkCtrl(GPIOD,ENABLE);

	//initialize the GPIO pin 12
	GPIO_Init(&led[0]);

	//initialize the GPIO pin 13
	GPIO_Init(&led[1]);

	/* Loop forever */
	while(1)
	{
		GPIO_ToggleOutputPin(GPIOD, PIN12);
		GPIO_ToggleOutputPin(GPIOD, PIN13);
		for(__vo uint16_t i = 0;i<10000;i++)
		{
			for(__vo uint16_t j=0;j<100;j++);
		}

	}
}
